### ISSUE TITLE
CT Assertion failed: validation failed for value:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#123]
Also in Basics and Density
```
buoyancy : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710839801916%22%2C%22timestamp%22%3A1710840137041%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
Error: Assertion failed: validation failed for value:
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at assert (validate.ts:32:16)
at validate (ReadOnlyProperty.ts:309:14)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (Mass.ts:561:44)
at updateSubmergedMassFraction (DensityBuoyancyModel.ts:355:13)
at Proxy.forEach
at forEach (DensityBuoyancyModel.ts:288:18)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1710839801916%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710839801916%22%2C%22timestamp%22%3A1710840137041%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1710839801916%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710839801916%22%2C%22timestamp%22%3A1710840137041%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710839801916%22%2C%22timestamp%22%3A1710840137041%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: validation failed for value: Infinity Property value not valid: Failed validation for validators[1]: Number value Infinity must be within rangeProperty value: [Range (min:0 max:1)]: value failed isValidValue: Infinity prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
Infinity
Property value not valid: Failed validation for validators[1]: Number value Infinity must be within rangeProperty value: [Range (min:0 max:1)]: value failed isValidValue: Infinity
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Scale.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: Infinity Property value not valid: Failed validation for validators[1]: Number value Infinity must be within rangeProperty value: [Range (min:0 max:1)]: value failed isValidValue: Infinity prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
Infinity
Property value not valid: Failed validation for validators[1]: Number value Infinity must be within rangeProperty value: [Range (min:0 max:1)]: value failed isValidValue: Infinity
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Cube.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: NaN Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Scale.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: NaN Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Scale.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: NaN Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Scale.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: NaN Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Scale.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: NaN Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/validate.js:28:17)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:236:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/axon/js/Property.js:48:11)
at Scale.updateSubmergedMassFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:403:46)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:251:14
at Proxy.forEach (<anonymous>)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710839801916/chipper/dist/js/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:191:19
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: validation failed for value: NaN Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN prunedValidator: {
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed for value:
NaN
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
```

**Comment by zepumph** [comment]
Fixed with a workaround over in https://github.com/phetsims/buoyancy/issues/124. CT should be clear next round.
