### ISSUE TITLE
CT:  Dynamic element metadata should match the archetype in the API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/buoyancy#153]
```
buoyancy : phet-io-studio-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1715373491158/studio/?sim=buoyancy&locales=*&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715373491158%22%2C%22timestamp%22%3A1715376753151%7D
Uncaught Error: Assertion failed: PhET-iO API error:
buoyancy.shapesScreen.model.objects.objectACapsule.objectA: 5. Dynamic element metadata should match the archetype in the API.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1715373491158/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:253:16)
at assertAPIError (phetioAPIValidation.ts:270:15)
at Array.forEach
at forEach (phetioAPIValidation.ts:263:18)
at checkDynamicInstanceAgainstArchetype (phetioAPIValidation.ts:181:17)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:213:6)
at notifyLoop (TinyEmitter.ts:196:13)
at emit (Sim.ts:1018:24)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1715373491158%2Fstudio%2F%3Fsim%3Dbuoyancy%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715373491158%22%2C%22timestamp%22%3A1715376753151%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1715373491158%2Fstudio%2F%3Fsim%3Dbuoyancy%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715373491158%22%2C%22timestamp%22%3A1715376753151%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1715373491158/studio/?sim=buoyancy&locales=*&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715373491158%22%2C%22timestamp%22%3A1715376753151%7D
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
...

id: "Sparky Node Puppeteer"
Snapshot from 5/10/2024, 2:38:11 PM
```

**Comment by zepumph** [comment]
This is very easy to reproduce. Open studio, go to shapes screen, change the block shape to anything else.

This likely started showing up because of #114. Basically the archetype says it's a CuboidIO, but then you create a DuckIO and the errors says, "hey, you didn't make something that validates against the archetype."  I'd like to discuss with @samreid and @AgustinVallejo to see how to proceed. Here are some ideas:

* Somehow tell the archetype that it is a MassIO, or create the archetype in a better, more general way (with updates to how to compare against a supertype form.
* Have a more general conversation about heterogenous PhET-iO groups, and make sure this is how we want to be serializing things.
* Something else!

**Comment by zepumph** [comment]
I created https://github.com/phetsims/buoyancy/issues/160 to solve this generally, so we don't overload a CT issue report.

**Comment by zepumph** [comment]
This has been fixed since fix in https://github.com/phetsims/buoyancy/issues/160
