### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#22]
```
buoyancy : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (buoyancy, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 6219ms
>> Production minification complete: 51210ms (3333587 bytes)
>> Debug minification complete: 1ms (8808091 bytes)
Building brand: phet-io
>> Webpack build complete: 4779ms
>> Production minification complete: 44715ms (3359864 bytes)
>> Debug minification complete: 41200ms (3643094 bytes)
>> No client guides found at ../phet-io-client-guides/buoyancy/, no guides being built.
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1627592226939/chipper/js/grunt/copySupplementalPhetioFiles.js:312:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1627592226939/chipper/js/grunt/buildRunnable.js:356:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1627592226939/chipper/js/grunt/Gruntfile.js:253:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1627592226939/chipper/js/grunt/Gruntfile.js:72:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error in fulfilling chunk Promise: [Error: TypeError: Cannot read property 'createTandem' of undefined
at new fS (http://localhost:34883/buoyancy/build/phet-io/buoyancy_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1168:1198134)
at new hV (http://localhost:34883/buoyancy/build/phet-io/buoyancy_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1168:2387379)
at PV.createModel (http://localhost:34883/buoyancy/build/phet-io/buoyancy_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1168:2392757)
at PV.initializeModel (http://localhost:34883/buoyancy/build/phet-io/buoyancy_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1168:868635)
at Array.<anonymous> (http://localhost:34883/buoyancy/build/phet-io/buoyancy_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1168:1146815)
at http://localhost:34883/buoyancy/build/phet-io/buoyancy_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1168:1147002]
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627593797663%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627593675194%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627594649296%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627595832946%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/phet-io-wrappers/mirror-inputs/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627595872113%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/studio/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627595595966%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/phet-io-wrappers/phet-io-wrappers-tests.html?sim=buoyancy&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: buoyancy: iframe API failed:
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25

Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefinedTypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/phet-io-wrappers/phet-io-wrappers-tests.html?sim=buoyancy
3 out of 4 tests passed. 1 failed.
SimTests: buoyancy: iframe API failed:
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25

Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefinedTypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM

----------------------------------

buoyancy : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1627592226939%22%2C%22timestamp%22%3A1627594493901%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new Scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/common/model/Scale.js:76:29)
at new BuoyancyIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/density-buoyancy-common/js/buoyancy/model/BuoyancyIntroModel.js:75:23)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/buoyancy/js/view/IntroScreen.js:24:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:935:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627592226939/joist/js/Sim.js:946:25
id: Bayes Chrome
Snapshot from 7/29/2021, 2:57:06 PM
```

**Comment by jonathanolson** [comment]
I believe this is now resolved.
