### ISSUE TITLE
CT x should be a finite number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#39]
```
buoyancy : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637637144406%22%2C%22timestamp%22%3A1637640907012%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/assert/js/assert.js:25:13)
at PrecisionSliderThumb.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/scenery/js/nodes/Node.js:1944:23)
at PrecisionSliderThumb.setCenterX (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/scenery/js/nodes/Node.js:2658:18)
at PrecisionSliderThumb.set centerX [as centerX] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/scenery/js/nodes/Node.js:2669:14)
at valueObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/sun/js/Slider.js:252:27)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/TinyEmitter.js:65:17)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:193:27)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:137:22)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:252:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/density-buoyancy-common/js/common/view/MaterialMassVolumeControlNode.js:194:42
id: Bayes Chrome
Snapshot from 11/22/2021, 8:12:24 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637637144406%22%2C%22timestamp%22%3A1637640131894%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/PhetioObject.js:474:27
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/PhetioObject.js:473:25
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Timer.js:26:21)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/TinyEmitter.js:77:49)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/joist/js/Sim.js:705:29)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:12:24 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637637144406%22%2C%22timestamp%22%3A1637660324287%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/ValidatorDef.js:281:45)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/validate.js:30:22)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/StateSchema.js:155:17)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:280:49)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:314:14)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:179:32)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:186:45)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/PhetioObject.js:316:52)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:181:14)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:12:24 PM

----------------------------------

buoyancy : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/phet-io-wrappers/input-record-and-playback/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637637144406%22%2C%22timestamp%22%3A1637661603052%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/ValidatorDef.js:281:45)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/validate.js:30:22)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/StateSchema.js:155:17)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:280:49)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:314:14)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:179:32)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:186:45)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/PhetioObject.js:316:52)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:181:14)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:12:24 PM

----------------------------------

buoyancy : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/studio/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637637144406%22%2C%22timestamp%22%3A1637643724302%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/ValidatorDef.js:281:45)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/validate.js:30:22)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/StateSchema.js:155:17)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:280:49)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:314:14)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:179:32)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:186:45)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/PhetioObject.js:316:52)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:181:14)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:12:24 PM

----------------------------------

buoyancy : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/studio/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637637144406%22%2C%22timestamp%22%3A1637662019325%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/ValidatorDef.js:281:45)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/validate.js:30:22)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/StateSchema.js:155:17)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:280:49)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:314:14)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/types/IOType.js:179:32)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:186:45)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/tandem/js/PhetioObject.js:316:52)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637637144406/chipper/dist/axon/js/Property.js:181:14)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:12:24 PM
```

**Comment by jonathanolson** [comment]
This is caused because the internal volume of the bottle can be changed to zero AND then it can be set to the CUSTOM mode. This means we have a non-zero internal mass, but zero volume. I'm not sure how the sim should even behave when in the custom mode with zero volume, and I have a slight preference to avoid this (OR to set the mass slider in this case to zero and disable the mass slider). Thoughts?

**Comment by DianaTavares** [comment]
In that case, We can change the min volume to 0.5L for the custom option (by adding a restriction, like the mass slider). The min mass is already 0.5 kg. 
I don't think that these values for the min mass and volume affect the learning goals of this screen, but I want to ask @ariel-phet  and @arouinfar for other thoughts. This will be the only place in the sim where the volume slider has a restriction. 

The bottle will have always something inside in the custom option, and the max density that this material can have is 200 kg/L
![image](https://user-images.githubusercontent.com/26031501/152404559-91f75df0-3d13-4f68-a99a-f996b7acbec1.png)

**Comment by ariel-phet** [comment]
@jonathanolson @DianaTavares 

I agree, there is no problem with having finite values for the minimums of mass and volume for the custom object, and in fact having minimums that are greater than zero seems completely appropriate and logical.

**Comment by arouinfar** [comment]
@DianaTavares's proposal sounds good to me too.

**Comment by jonathanolson** [comment]
Implemented above, @DianaTavares can you give it a try?

**Comment by DianaTavares** [comment]
It works! Thanks!!
