### ISSUE TITLE
CT All descendants must be disposed by the next frame

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#40]
```
buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638749266402%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:539:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:538:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/joist/js/Sim.js:762:25)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638758828657%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:539:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:538:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/joist/js/Sim.js:762:25)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638789106909%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/ValidatorDef.js:299:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/validate.js:33:18)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/StateSchema.js:173:9)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:308:43)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:350:10)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:194:24)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Property.js:221:35)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:356:46)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Property.js:216:10)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638804603077%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:539:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:538:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/joist/js/Sim.js:762:25)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/phet-io-wrappers/input-record-and-playback/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638761402782%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/ValidatorDef.js:299:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/validate.js:33:18)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/StateSchema.js:173:9)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:308:43)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:350:10)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:194:24)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Property.js:221:35)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:356:46)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Property.js:216:10)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/phet-io-wrappers/input-record-and-playback/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638788402076%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: NaN
Error: Assertion failed: value failed isValidValue: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/ValidatorDef.js:299:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/validate.js:33:18)
at StateSchema.checkStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/StateSchema.js:173:9)
at IOType.isStateObjectValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:308:43)
at IOType.validateStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:350:10)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/types/IOType.js:194:24)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Property.js:221:35)
at DerivedProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:356:46)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Property.js:216:10)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/phet-io-wrappers/input-record-and-playback/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638804602637%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:539:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:538:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/joist/js/Sim.js:762:25)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/phet-io-wrappers/state/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638748935030%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:539:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:538:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/joist/js/Sim.js:762:25)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM

----------------------------------

buoyancy : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/studio/?sim=buoyancy&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638747625834%22%2C%22timestamp%22%3A1638750746420%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.inputEnabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:539:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/tandem/js/PhetioObject.js:538:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638747625834/chipper/dist/js/joist/js/Sim.js:762:25)
id: Bayes Chrome
Snapshot from 12/5/2021, 4:40:25 PM
```

**Comment by KatieWoe** [comment]
```
buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647607030739%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:794:25)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM
```

**Comment by KatieWoe** [comment]
May be related:
```
buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651057211527/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651057211527%22%2C%22timestamp%22%3A1651063827156%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: already disposed
Error: Assertion failed: already disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651057211527/assert/js/assert.js:28:13)
at assert (Tandem.js:305:14)
at dispose (Tandem.js:215:24)
at removePhetioObject (PhetioObject.ts:642:18)
at dispose (Property.ts:471:10)
at call (PhetioObject.ts:177:21)
at dispose (Mass.ts:638:32)
at call (PhetioObject.ts:177:21)
at dispose (BuoyancyShapesModel.ts:185:16)
at listener (TinyEmitter.ts:93:8)
id: Bayes Chrome
Snapshot from 4/27/2022, 5:00:11 AM
```

**Comment by jonathanolson** [comment]
This is caused by https://github.com/phetsims/buoyancy/issues/61 not being completed.

**Comment by zepumph** [comment]
CT has been clear for the last 30 hours. I'll reopen if this comes back to us.
