### ISSUE TITLE
CT: Assertion failed: value failed isValidValue: -0.00003925153758645465

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/buoyancy#44]
Possibly related to https://github.com/phetsims/buoyancy/issues/36, but a different stack trace, and not NaN.

```
buoyancy : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646310309850%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: -0.00003925153758645465
Error: Assertion failed: value failed isValidValue: -0.00003925153758645465
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/ValidatorDef.js:299:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/validate.js:33:18)
at NumberProperty.validateNumberAndRangeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/NumberProperty.js:102:9)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/NumberProperty.js:245:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/NumberProperty.js:134:68
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/Property.js:228:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/Property.js:159:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/Property.js:298:10)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM
```

**Comment by zepumph** [comment]
CT has been clear for the last 30 hours. I'll reopen if this comes back to us.
