### ISSUE TITLE
CT empty volume should be non-negative

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#49]
```
buoyancy : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1648981494042%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: empty volume should be non-negative
Error: Assertion failed: empty volume should be non-negative
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at BoatBasin.getEmptyVolume (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/common/model/Basin.js:103:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/buoyancy/view/BoatView.js:124:40
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at InterpolatedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:218:23)
at InterpolatedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:147:14)
at InterpolatedProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:288:10)
at InterpolatedProperty.setRatio (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/common/model/InterpolatedProperty.js:39:16)
at Boat.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/buoyancy/model/Boat.js:73:44)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1649051106333%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at TinyProperty.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:112:7)
at TinyProperty.unlink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyProperty.js:148:10)
at ColorProperty.unlink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:348:23)
at DynamicProperty.onPropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/DynamicProperty.js:200:37)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:147:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:288:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/common/view/MaterialMassVolumeControlNode.js:170:34
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1649071124236%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at TinyProperty.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:112:7)
at TinyProperty.unlink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyProperty.js:148:10)
at ColorProperty.unlink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:348:23)
at DynamicProperty.onPropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/DynamicProperty.js:200:37)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:147:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:288:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/common/view/MaterialMassVolumeControlNode.js:170:34
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1648939505753%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:529:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/joist/js/Sim.js:801:25)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1648948725207%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:529:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/joist/js/Sim.js:801:25)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1648990433913%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:529:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/joist/js/Sim.js:801:25)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1649013688806%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:529:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/joist/js/Sim.js:801:25)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1649031398469%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
Error: Assertion failed: All descendants must be disposed by the next frame: buoyancy.shapesScreen.model.primaryMass.radiusProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:529:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/joist/js/Sim.js:801:25)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1649052408144%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: already disposed
Error: Assertion failed: already disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at Tandem.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/Tandem.js:290:15)
at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/Tandem.js:197:25)
at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:535:19)
at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/Property.js:420:11)
at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:117:22)
at Ellipsoid.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/common/model/Mass.js:504:33)
at Ellipsoid.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:117:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/density-buoyancy-common/js/buoyancy/model/BuoyancyShapesModel.js:143:17
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM
```

**Comment by zepumph** [comment]
@jonathanolson helped @samreid and I see that Basin.getEmptyVolume needs to work when a `y` is Infinity, but it `Basin.getDisplacedVolume` cares about the entire volume of its masses, even if they aren't fully in the boat. I think we got this bug, but let's make sure we have it covered on CT.

**Comment by zepumph** [comment]
CT looks good. Closing
