### ISSUE TITLE
CT already disposed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#63]
```
buoyancy : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653485174776/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653485174776%22%2C%22timestamp%22%3A1653489005581%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: already disposed
Error: Assertion failed: already disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653485174776/assert/js/assert.js:28:13)
at assert (Tandem.js:305:14)
at dispose (Tandem.js:215:24)
at removePhetioObject (PhetioObject.ts:642:18)
at dispose (Property.ts:467:10)
at call (PhetioObject.ts:177:21)
at dispose (Mass.ts:639:32)
at call (PhetioObject.ts:177:21)
at dispose (BuoyancyShapesModel.ts:186:16)
at listener (TinyEmitter.ts:93:8)
id: Bayes Chrome
Snapshot from 5/25/2022, 7:26:14 AM
```

**Comment by zepumph** [comment]
CT has been clear for the last 30 hours. I'll reopen if this comes back to us.
