### ISSUE TITLE
CT Assertion failed: density should be finite, but it was . . . 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#69]
```
buoyancy : pan-and-zoom-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686567350831%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/assert/js/assert.js:28:13)
at assert (Material.ts:101:14)
at (Material.ts:118:11)
at createCustomMaterial (Material.ts:138:20)
at createCustomSolidMaterial (MaterialMassVolumeControlNode.ts:208:44)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:316:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:65:10)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686563111425%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686567350831%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686563111425%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686567350831%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686567350831%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed
[PAGE ERROR] Error: Error: Assertion failed
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/assert/js/assert.js:28:13)
at new Material (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/model/Material.js:40:15)
at Material.createCustomMaterial (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/model/Material.js:56:12)
at Material.createCustomSolidMaterial (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/model/Material.js:76:21)
at http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/view/MaterialMassVolumeControlNode.js:166:45
at TinyProperty.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at NumberProperty._notifyListeners (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/ReadOnlyProperty.js:240:23)
at NumberProperty.unguardedSet (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/ReadOnlyProperty.js:189:14)
at NumberProperty.set (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/ReadOnlyProperty.js:174:12)
at NumberProperty.set (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/Property.js:58:11)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 6/12/2023, 3:45:11 AM

----------------------------------

buoyancy : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686563539299%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/assert/js/assert.js:28:13)
at assert (Material.ts:101:14)
at (Material.ts:118:11)
at createCustomMaterial (Material.ts:138:20)
at createCustomSolidMaterial (MaterialMassVolumeControlNode.ts:208:44)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:316:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:65:10)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686563111425%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686563539299%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686563111425%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686563539299%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686563111425%22%2C%22timestamp%22%3A1686563539299%7D&ea&brand=phet-io&phetioStandalone&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed
[PAGE ERROR] Error: Error: Assertion failed
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/assert/js/assert.js:28:13)
at new Material (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/model/Material.js:40:15)
at Material.createCustomMaterial (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/model/Material.js:56:12)
at Material.createCustomSolidMaterial (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/model/Material.js:76:21)
at http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/density-buoyancy-common/js/common/view/MaterialMassVolumeControlNode.js:166:45
at TinyProperty.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at NumberProperty._notifyListeners (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/ReadOnlyProperty.js:240:23)
at NumberProperty.unguardedSet (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/ReadOnlyProperty.js:189:14)
at NumberProperty.set (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/ReadOnlyProperty.js:174:12)
at NumberProperty.set (http://127.0.0.1/continuous-testing/ct-snapshots/1686563111425/chipper/dist/js/axon/js/Property.js:58:11)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 6/12/2023, 3:45:11 AM
```

**Comment by zepumph** [comment]
CT has been clear for the last 30 hours. I'll reopen if this comes back to us.
