### ISSUE TITLE
CT perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy#8]
```
buoyancy : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (buoyancy, brands: phet)
Building brand: phet
>> Webpack build complete: 5465ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: nested strings are not allowed outside of a11y string object for key: mode.sameMass
at Object.getStringFromMap (/data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/common/ChipperStringUtils.js:156:63)
at /data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/getStringMap.js:207:46
at Array.forEach (<anonymous>:null:null)
at /data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/getStringMap.js:202:15
at Array.forEach (<anonymous>:null:null)
at /data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/getStringMap.js:201:23
at Array.forEach (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/getStringMap.js:153:24)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/buildRunnable.js:132:21)
at /data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/Gruntfile.js:254:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1611776810613/chipper/js/grunt/Gruntfile.js:73:7)

Full Error details:
{
"generatedMessage": false,
"code": "ERR_ASSERTION",
"expected": true,
"operator": "=="
}
Snapshot from 1/27/2021, 12:46:50 PM
```

**Comment by KatieWoe** [comment]
Also in density

**Comment by jonathanolson** [comment]
Handled with the above commit, closing.
